# What is NumPy?

### NumPy is a python library used for working with arrays.

* It also has functions for working in domain of linear algebra, fourier transform, and matrices.
* In Python we have lists that serve the purpose of arrays, but they are slow to process.
* NumPy aims to provide an array object that is up to 50x faster that traditional Python lists.
* The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.
## Why is NumPy Faster Than Lists?
* NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

* This behavior is called locality of reference in computer science.

* This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

In [51]:
import numpy as np

# Creating An Array

In [52]:
l=[2,5,24,8]
a=np.array(l)
a

array([ 2,  5, 24,  8])

# MultiDimensional Array

In [16]:
m=([[2,4,6],[1,3,5]])
s=np.array(m)
s

array([[2, 4, 6],
       [1, 3, 5]])

# Numpy Functions

In [20]:
s.shape   #gives (row,column)value

(2, 3)

In [21]:
x=np.arange(1,16,4)   #arange ==> (start,end,increment)
x

array([ 1,  5,  9, 13])

In [23]:
y=np.arange(50,0,-2)
y

array([50, 48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18,
       16, 14, 12, 10,  8,  6,  4,  2])

In [28]:
y.reshape(5,5)   #reshape changes dimension

array([[50, 48, 46, 44, 42],
       [40, 38, 36, 34, 32],
       [30, 28, 26, 24, 22],
       [20, 18, 16, 14, 12],
       [10,  8,  6,  4,  2]])

In [34]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [36]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [40]:
np.diag(x)

array([[ 1,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 13]])

In [41]:
np.array(s*3)

array([[ 6, 12, 18],
       [ 3,  9, 15]])

In [42]:
np.array([1,3,5]*3)

array([1, 3, 5, 1, 3, 5, 1, 3, 5])

In [43]:
np.repeat([1,4,6],3)

array([1, 1, 1, 4, 4, 4, 6, 6, 6])

In [45]:
np.vstack([s,s*2])

array([[ 2,  4,  6],
       [ 1,  3,  5],
       [ 4,  8, 12],
       [ 2,  6, 10]])

In [55]:
np.hstack([x,x*3])

array([ 1,  5,  9, 13,  3, 15, 27, 39])

# Operations

In [69]:
p=np.array([1,3,5])
q=np.array([9,7,5])

In [70]:
print(p + q)

[10 10 10]


In [71]:
print(q - p)

[8 4 0]


In [72]:
p.dot(q)

55

In [73]:
p ** 3

array([  1,  27, 125], dtype=int32)

In [75]:
s.T

array([[2, 1],
       [4, 3],
       [6, 5]])

In [77]:
s.T.shape

(3, 2)

In [80]:
s.dtype

dtype('int32')

In [84]:
a=p.astype('f')
a.dtype

dtype('float32')

In [85]:
p.sum()

9

In [86]:
q.mean()

7.0

In [87]:
q.max()

9

In [88]:
q.min()

5

In [92]:
q.argmax()  

0

In [93]:
q.argmin()

2

In [91]:
q.std()

1.632993161855452

# Indexing/Slicing

In [94]:
w=np.arange(12) ** 3
w

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000,
       1331], dtype=int32)

In [95]:
w[3],w[-3],w[2:5]

(27, 729, array([ 8, 27, 64], dtype=int32))

In [110]:
q=np.arange(36)
q.resize((6,6))
q

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [111]:
q[2,2]

14

In [113]:
q[q<4]

array([0, 1, 2, 3])

In [114]:
q[:-3,2:]

array([[ 2,  3,  4,  5],
       [ 8,  9, 10, 11],
       [14, 15, 16, 17]])

# Iterating Over Arrays

In [116]:
t=np.random.randint(1,11,(4,3))
t

array([[ 6,  8,  9],
       [ 1,  4, 10],
       [ 3,  8,  6],
       [ 5,  8,  9]])

In [117]:
for row in t:
    print(row)

[6 8 9]
[ 1  4 10]
[3 8 6]
[5 8 9]


In [118]:
for i in range(len(t)):
    print(t[i])

[6 8 9]
[ 1  4 10]
[3 8 6]
[5 8 9]


In [119]:
for i,row in enumerate(t):
    print('row',i,'is',row)

row 0 is [6 8 9]
row 1 is [ 1  4 10]
row 2 is [3 8 6]
row 3 is [5 8 9]


In [121]:
t2=t** 2
t2

array([[ 36,  64,  81],
       [  1,  16, 100],
       [  9,  64,  36],
       [ 25,  64,  81]], dtype=int32)

In [122]:
for i,j in zip(t,t2):
    print(i,'+',j,'=',i+j)

[6 8 9] + [36 64 81] = [42 72 90]
[ 1  4 10] + [  1  16 100] = [  2  20 110]
[3 8 6] + [ 9 64 36] = [12 72 42]
[5 8 9] + [25 64 81] = [30 72 90]
